

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=70BA0A3B40E2B9899612678C078FC24A
CopyrightNotice=Copyright GYQ

; 在DefaultGame.ini文件中,我们可以指定我们的AbilitySystemGlobals类
; 作用：替换 GAS 的全局单例类，把引擎默认的 UGameplayAbilities.AbilitySystemGlobals 替换成你项目自定义的 AAuraAbilitySystemGlobals。
; 用途：重写 InitGlobalActorData()、CreateGameplayEffectContext() 等函数，
; 用来生成你自定义的 FAuraGameplayEffectContext，和你前面写的网络序列化结构体配套。
[/Script/GameplayAbilities.AbilitySystemGlobals]
+AbilitySystemGlobalsClassName="/Script/Aura.AuraAbilitySystemGlobals"